export interface CurrencyOption {
  code: string;
  name: string;
  country: string;
  symbol: string;
  flag: string;
}

export const POPULAR_CURRENCIES: CurrencyOption[] = [
  { code: "USD", name: "US Dollar", country: "United States", symbol: "$", flag: "🇺🇸" },
  { code: "EUR", name: "Euro", country: "European Union", symbol: "€", flag: "🇪🇺" },
  { code: "GBP", name: "British Pound", country: "United Kingdom", symbol: "£", flag: "🇬🇧" },
  { code: "INR", name: "Indian Rupee", country: "India", symbol: "₹", flag: "🇮🇳" },
  { code: "JPY", name: "Japanese Yen", country: "Japan", symbol: "¥", flag: "🇯🇵" },
  { code: "AUD", name: "Australian Dollar", country: "Australia", symbol: "A$", flag: "🇦🇺" },
  { code: "CAD", name: "Canadian Dollar", country: "Canada", symbol: "C$", flag: "🇨🇦" },
  { code: "CHF", name: "Swiss Franc", country: "Switzerland", symbol: "CHF", flag: "🇨🇭" },
  { code: "SGD", name: "Singapore Dollar", country: "Singapore", symbol: "S$", flag: "🇸🇬" },
  { code: "AED", name: "UAE Dirham", country: "United Arab Emirates", symbol: "AED", flag: "🇦🇪" },
  { code: "HKD", name: "Hong Kong Dollar", country: "Hong Kong", symbol: "HK$", flag: "🇭🇰" },
  { code: "NZD", name: "New Zealand Dollar", country: "New Zealand", symbol: "NZ$", flag: "🇳🇿" },
];

export const ALL_CURRENCIES: CurrencyOption[] = [
  { code: "AED", name: "UAE Dirham", country: "United Arab Emirates", symbol: "AED", flag: "🇦🇪" },
  { code: "AFN", name: "Afghan Afghani", country: "Afghanistan", symbol: "؋", flag: "🇦🇫" },
  { code: "ALL", name: "Albanian Lek", country: "Albania", symbol: "L", flag: "🇦🇱" },
  { code: "AMD", name: "Armenian Dram", country: "Armenia", symbol: "֏", flag: "🇦🇲" },
  { code: "ANG", name: "Netherlands Antillean Guilder", country: "Curaçao, Sint Maarten", symbol: "ƒ", flag: "🇨🇼" },
  { code: "AOA", name: "Angolan Kwanza", country: "Angola", symbol: "Kz", flag: "🇦🇴" },
  { code: "ARS", name: "Argentine Peso", country: "Argentina", symbol: "$", flag: "🇦🇷" },
  { code: "AUD", name: "Australian Dollar", country: "Australia", symbol: "A$", flag: "🇦🇺" },
  { code: "AWG", name: "Aruban Florin", country: "Aruba", symbol: "ƒ", flag: "🇦🇼" },
  { code: "AZN", name: "Azerbaijani Manat", country: "Azerbaijan", symbol: "₼", flag: "🇦🇿" },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", country: "Bosnia and Herzegovina", symbol: "KM", flag: "🇧🇦" },
  { code: "BBD", name: "Barbadian Dollar", country: "Barbados", symbol: "Bds$", flag: "🇧🇧" },
  { code: "BDT", name: "Bangladeshi Taka", country: "Bangladesh", symbol: "৳", flag: "🇧🇩" },
  { code: "BGN", name: "Bulgarian Lev", country: "Bulgaria", symbol: "лв", flag: "🇧🇬" },
  { code: "BHD", name: "Bahraini Dinar", country: "Bahrain", symbol: ".د.ب", flag: "🇧🇭" },
  { code: "BIF", name: "Burundian Franc", country: "Burundi", symbol: "FBu", flag: "🇧🇮" },
  { code: "BMD", name: "Bermudian Dollar", country: "Bermuda", symbol: "$", flag: "🇧🇲" },
  { code: "BND", name: "Brunei Dollar", country: "Brunei", symbol: "B$", flag: "🇧🇳" },
  { code: "BOB", name: "Bolivian Boliviano", country: "Bolivia", symbol: "Bs.", flag: "🇧🇴" },
  { code: "BRL", name: "Brazilian Real", country: "Brazil", symbol: "R$", flag: "🇧🇷" },
  { code: "BSD", name: "Bahamian Dollar", country: "Bahamas", symbol: "$", flag: "🇧🇸" },
  { code: "BTN", name: "Bhutanese Ngultrum", country: "Bhutan", symbol: "Nu.", flag: "🇧🇹" },
  { code: "BWP", name: "Botswanan Pula", country: "Botswana", symbol: "P", flag: "🇧🇼" },
  { code: "BYN", name: "Belarusian Ruble", country: "Belarus", symbol: "Br", flag: "🇧🇾" },
  { code: "BZD", name: "Belize Dollar", country: "Belize", symbol: "BZ$", flag: "🇧🇿" },
  { code: "CAD", name: "Canadian Dollar", country: "Canada", symbol: "C$", flag: "🇨🇦" },
  { code: "CDF", name: "Congolese Franc", country: "DR Congo", symbol: "FC", flag: "🇨🇩" },
  { code: "CHF", name: "Swiss Franc", country: "Switzerland", symbol: "CHF", flag: "🇨🇭" },
  { code: "CLP", name: "Chilean Peso", country: "Chile", symbol: "$", flag: "🇨🇱" },
  { code: "CNY", name: "Chinese Yuan", country: "China", symbol: "¥", flag: "🇨🇳" },
  { code: "COP", name: "Colombian Peso", country: "Colombia", symbol: "$", flag: "🇨🇴" },
  { code: "CRC", name: "Costa Rican Colón", country: "Costa Rica", symbol: "₡", flag: "🇨🇷" },
  { code: "CUP", name: "Cuban Peso", country: "Cuba", symbol: "$", flag: "🇨🇺" },
  { code: "CVE", name: "Cape Verdean Escudo", country: "Cape Verde", symbol: "$", flag: "🇨🇻" },
  { code: "CZK", name: "Czech Koruna", country: "Czech Republic", symbol: "Kč", flag: "🇨🇿" },
  { code: "DJF", name: "Djiboutian Franc", country: "Djibouti", symbol: "Fdj", flag: "🇩🇯" },
  { code: "DKK", name: "Danish Krone", country: "Denmark", symbol: "kr", flag: "🇩🇰" },
  { code: "DOP", name: "Dominican Peso", country: "Dominican Republic", symbol: "RD$", flag: "🇩🇴" },
  { code: "DZD", name: "Algerian Dinar", country: "Algeria", symbol: "دج", flag: "🇩🇿" },
  { code: "EGP", name: "Egyptian Pound", country: "Egypt", symbol: "E£", flag: "🇪🇬" },
  { code: "ERN", name: "Eritrean Nakfa", country: "Eritrea", symbol: "Nfk", flag: "🇪🇷" },
  { code: "ETB", name: "Ethiopian Birr", country: "Ethiopia", symbol: "Br", flag: "🇪🇹" },
  { code: "EUR", name: "Euro", country: "European Union", symbol: "€", flag: "🇪🇺" },
  { code: "FJD", name: "Fijian Dollar", country: "Fiji", symbol: "FJ$", flag: "🇫🇯" },
  { code: "FKP", name: "Falkland Islands Pound", country: "Falkland Islands", symbol: "£", flag: "🇫🇰" },
  { code: "GBP", name: "British Pound", country: "United Kingdom", symbol: "£", flag: "🇬🇧" },
  { code: "GEL", name: "Georgian Lari", country: "Georgia", symbol: "₾", flag: "🇬🇪" },
  { code: "GHS", name: "Ghanaian Cedi", country: "Ghana", symbol: "GH₵", flag: "🇬🇭" },
  { code: "GIP", name: "Gibraltar Pound", country: "Gibraltar", symbol: "£", flag: "🇬🇮" },
  { code: "GMD", name: "Gambian Dalasi", country: "Gambia", symbol: "D", flag: "🇬🇲" },
  { code: "GNF", name: "Guinean Franc", country: "Guinea", symbol: "FG", flag: "🇬🇳" },
  { code: "GTQ", name: "Guatemalan Quetzal", country: "Guatemala", symbol: "Q", flag: "🇬🇹" },
  { code: "GYD", name: "Guyanaese Dollar", country: "Guyana", symbol: "G$", flag: "🇬🇾" },
  { code: "HKD", name: "Hong Kong Dollar", country: "Hong Kong", symbol: "HK$", flag: "🇭🇰" },
  { code: "HNL", name: "Honduran Lempira", country: "Honduras", symbol: "L", flag: "🇭🇳" },
  { code: "HRK", name: "Croatian Kuna", country: "Croatia", symbol: "kn", flag: "🇭🇷" },
  { code: "HTG", name: "Haitian Gourde", country: "Haiti", symbol: "G", flag: "🇭🇹" },
  { code: "HUF", name: "Hungarian Forint", country: "Hungary", symbol: "Ft", flag: "🇭🇺" },
  { code: "IDR", name: "Indonesian Rupiah", country: "Indonesia", symbol: "Rp", flag: "🇮🇩" },
  { code: "ILS", name: "Israeli New Shekel", country: "Israel", symbol: "₪", flag: "🇮🇱" },
  { code: "INR", name: "Indian Rupee", country: "India", symbol: "₹", flag: "🇮🇳" },
  { code: "IQD", name: "Iraqi Dinar", country: "Iraq", symbol: "ع.د", flag: "🇮🇶" },
  { code: "IRR", name: "Iranian Rial", country: "Iran", symbol: "﷼", flag: "🇮🇷" },
  { code: "ISK", name: "Icelandic Króna", country: "Iceland", symbol: "kr", flag: "🇮🇸" },
  { code: "JMD", name: "Jamaican Dollar", country: "Jamaica", symbol: "J$", flag: "🇯🇲" },
  { code: "JOD", name: "Jordanian Dinar", country: "Jordan", symbol: "JD", flag: "🇯🇴" },
  { code: "JPY", name: "Japanese Yen", country: "Japan", symbol: "¥", flag: "🇯🇵" },
  { code: "KES", name: "Kenyan Shilling", country: "Kenya", symbol: "KSh", flag: "🇰🇪" },
  { code: "KGS", name: "Kyrgystani Som", country: "Kyrgyzstan", symbol: "с", flag: "🇰🇬" },
  { code: "KHR", name: "Cambodian Riel", country: "Cambodia", symbol: "៛", flag: "🇰🇭" },
  { code: "KMF", name: "Comorian Franc", country: "Comoros", symbol: "CF", flag: "🇰🇲" },
  { code: "KRW", name: "South Korean Won", country: "South Korea", symbol: "₩", flag: "🇰🇷" },
  { code: "KWD", name: "Kuwaiti Dinar", country: "Kuwait", symbol: "KD", flag: "🇰🇼" },
  { code: "KYD", name: "Cayman Islands Dollar", country: "Cayman Islands", symbol: "$", flag: "🇰🇾" },
  { code: "KZT", name: "Kazakhstani Tenge", country: "Kazakhstan", symbol: "₸", flag: "🇰🇿" },
  { code: "LAK", name: "Laotian Kip", country: "Laos", symbol: "₭", flag: "🇱🇦" },
  { code: "LBP", name: "Lebanese Pound", country: "Lebanon", symbol: "ل.ل", flag: "🇱🇧" },
  { code: "LKR", name: "Sri Lankan Rupee", country: "Sri Lanka", symbol: "Rs", flag: "🇱🇰" },
  { code: "LRD", name: "Liberian Dollar", country: "Liberia", symbol: "$", flag: "🇱🇷" },
  { code: "LSL", name: "Lesotho Loti", country: "Lesotho", symbol: "L", flag: "🇱🇸" },
  { code: "LYD", name: "Libyan Dinar", country: "Libya", symbol: "LD", flag: "🇱🇾" },
  { code: "MAD", name: "Moroccan Dirham", country: "Morocco", symbol: "MAD", flag: "🇲🇦" },
  { code: "MDL", name: "Moldovan Leu", country: "Moldova", symbol: "L", flag: "🇲🇩" },
  { code: "MGA", name: "Malagasy Ariary", country: "Madagascar", symbol: "Ar", flag: "🇲🇬" },
  { code: "MKD", name: "Macedonian Denar", country: "North Macedonia", symbol: "ден", flag: "🇲🇰" },
  { code: "MMK", name: "Myanmar Kyat", country: "Myanmar", symbol: "K", flag: "🇲🇲" },
  { code: "MNT", name: "Mongolian Tugrik", country: "Mongolia", symbol: "₮", flag: "🇲🇳" },
  { code: "MOP", name: "Macanese Pataca", country: "Macau", symbol: "MOP$", flag: "🇲🇴" },
  { code: "MRU", name: "Mauritanian Ouguiya", country: "Mauritania", symbol: "UM", flag: "🇲🇷" },
  { code: "MUR", name: "Mauritian Rupee", country: "Mauritius", symbol: "₨", flag: "🇲🇺" },
  { code: "MVR", name: "Maldivian Rufiyaa", country: "Maldives", symbol: "Rf", flag: "🇲🇻" },
  { code: "MWK", name: "Malawian Kwacha", country: "Malawi", symbol: "MK", flag: "🇲🇼" },
  { code: "MXN", name: "Mexican Peso", country: "Mexico", symbol: "$", flag: "🇲🇽" },
  { code: "MYR", name: "Malaysian Ringgit", country: "Malaysia", symbol: "RM", flag: "🇲🇾" },
  { code: "MZN", name: "Mozambican Metical", country: "Mozambique", symbol: "MT", flag: "🇲🇿" },
  { code: "NAD", name: "Namibian Dollar", country: "Namibia", symbol: "N$", flag: "🇳🇦" },
  { code: "NGN", name: "Nigerian Naira", country: "Nigeria", symbol: "₦", flag: "🇳🇬" },
  { code: "NIO", name: "Nicaraguan Córdoba", country: "Nicaragua", symbol: "C$", flag: "🇳🇮" },
  { code: "NOK", name: "Norwegian Krone", country: "Norway", symbol: "kr", flag: "🇳🇴" },
  { code: "NPR", name: "Nepalese Rupee", country: "Nepal", symbol: "रू", flag: "🇳🇵" },
  { code: "NZD", name: "New Zealand Dollar", country: "New Zealand", symbol: "NZ$", flag: "🇳🇿" },
  { code: "OMR", name: "Omani Rial", country: "Oman", symbol: "OMR", flag: "🇴🇲" },
  { code: "PAB", name: "Panamanian Balboa", country: "Panama", symbol: "B/.", flag: "🇵🇦" },
  { code: "PEN", name: "Peruvian Sol", country: "Peru", symbol: "S/.", flag: "🇵🇪" },
  { code: "PGK", name: "Papua New Guinean Kina", country: "Papua New Guinea", symbol: "K", flag: "🇵🇬" },
  { code: "PHP", name: "Philippine Peso", country: "Philippines", symbol: "₱", flag: "🇵🇭" },
  { code: "PKR", name: "Pakistani Rupee", country: "Pakistan", symbol: "₨", flag: "🇵🇰" },
  { code: "PLN", name: "Polish Zloty", country: "Poland", symbol: "zł", flag: "🇵🇱" },
  { code: "PYG", name: "Paraguayan Guarani", country: "Paraguay", symbol: "₲", flag: "🇵🇾" },
  { code: "QAR", name: "Qatari Rial", country: "Qatar", symbol: "QR", flag: "🇶🇦" },
  { code: "RON", name: "Romanian Leu", country: "Romania", symbol: "lei", flag: "🇷🇴" },
  { code: "RSD", name: "Serbian Dinar", country: "Serbia", symbol: "din.", flag: "🇷🇸" },
  { code: "RUB", name: "Russian Ruble", country: "Russia", symbol: "₽", flag: "🇷🇺" },
  { code: "RWF", name: "Rwandan Franc", country: "Rwanda", symbol: "RF", flag: "🇷🇼" },
  { code: "SAR", name: "Saudi Riyal", country: "Saudi Arabia", symbol: "SR", flag: "🇸🇦" },
  { code: "SBD", name: "Solomon Islands Dollar", country: "Solomon Islands", symbol: "SI$", flag: "🇸🇧" },
  { code: "SCR", name: "Seychellois Rupee", country: "Seychelles", symbol: "SR", flag: "🇸🇨" },
  { code: "SDG", name: "Sudanese Pound", country: "Sudan", symbol: "SDG", flag: "🇸🇩" },
  { code: "SEK", name: "Swedish Krona", country: "Sweden", symbol: "kr", flag: "🇸🇪" },
  { code: "SGD", name: "Singapore Dollar", country: "Singapore", symbol: "S$", flag: "🇸🇬" },
  { code: "SHP", name: "Saint Helena Pound", country: "Saint Helena", symbol: "£", flag: "🇸🇭" },
  { code: "SLL", name: "Sierra Leonean Leone", country: "Sierra Leone", symbol: "Le", flag: "🇸🇱" },
  { code: "SOS", name: "Somali Shilling", country: "Somalia", symbol: "Sh.So.", flag: "🇸🇴" },
  { code: "SRD", name: "Surinamese Dollar", country: "Suriname", symbol: "$", flag: "🇸🇷" },
  { code: "STN", name: "São Tomé & Príncipe Dobra", country: "São Tomé and Príncipe", symbol: "Db", flag: "🇸🇹" },
  { code: "SYP", name: "Syrian Pound", country: "Syria", symbol: "£S", flag: "🇸🇾" },
  { code: "SZL", name: "Swazi Lilangeni", country: "Eswatini", symbol: "E", flag: "🇸🇿" },
  { code: "THB", name: "Thai Baht", country: "Thailand", symbol: "฿", flag: "🇹🇭" },
  { code: "TJS", name: "Tajikistani Somoni", country: "Tajikistan", symbol: "SM", flag: "🇹🇯" },
  { code: "TMT", name: "Turkmenistani Manat", country: "Turkmenistan", symbol: "T", flag: "🇹🇲" },
  { code: "TND", name: "Tunisian Dinar", country: "Tunisia", symbol: "DT", flag: "🇹🇳" },
  { code: "TOP", name: "Tongan Paʻanga", country: "Tonga", symbol: "T$", flag: "🇹🇴" },
  { code: "TRY", name: "Turkish Lira", country: "Turkey", symbol: "₺", flag: "🇹🇷" },
  { code: "TTD", name: "Trinidad & Tobago Dollar", country: "Trinidad and Tobago", symbol: "TT$", flag: "🇹🇹" },
  { code: "TWD", name: "New Taiwan Dollar", country: "Taiwan", symbol: "NT$", flag: "🇹🇼" },
  { code: "TZS", name: "Tanzanian Shilling", country: "Tanzania", symbol: "TSh", flag: "🇹🇿" },
  { code: "UAH", name: "Ukrainian Hryvnia", country: "Ukraine", symbol: "₴", flag: "🇺🇦" },
  { code: "UGX", name: "Ugandan Shilling", country: "Uganda", symbol: "USh", flag: "🇺🇬" },
  { code: "USD", name: "US Dollar", country: "United States", symbol: "$", flag: "🇺🇸" },
  { code: "UYU", name: "Uruguayan Peso", country: "Uruguay", symbol: "$U", flag: "🇺🇾" },
  { code: "UZS", name: "Uzbekistani Som", country: "Uzbekistan", symbol: "so'm", flag: "🇺🇿" },
  { code: "VES", name: "Venezuelan Bolívar", country: "Venezuela", symbol: "Bs.S", flag: "🇻🇪" },
  { code: "VND", name: "Vietnamese Dong", country: "Vietnam", symbol: "₫", flag: "🇻🇳" },
  { code: "VUV", name: "Vanuatu Vatu", country: "Vanuatu", symbol: "VT", flag: "🇻🇺" },
  { code: "WST", name: "Samoan Tala", country: "Samoa", symbol: "WS$", flag: "🇼🇸" },
  { code: "XAF", name: "Central African CFA Franc", country: "Cameroon, CAR, Chad, Congo, Gabon", symbol: "FCFA", flag: "🇨🇲" },
  { code: "XCD", name: "East Caribbean Dollar", country: "Antigua, Dominica, Grenada, Saint Lucia", symbol: "EC$", flag: "🇦🇬" },
  { code: "XOF", name: "West African CFA Franc", country: "Senegal, Ivory Coast, Benin, Mali", symbol: "CFA", flag: "🇸🇳" },
  { code: "XPF", name: "CFP Franc", country: "French Polynesia, New Caledonia", symbol: "CFPF", flag: "🇵🇫" },
  { code: "YER", name: "Yemeni Rial", country: "Yemen", symbol: "﷼", flag: "🇾🇪" },
  { code: "ZAR", name: "South African Rand", country: "South Africa", symbol: "R", flag: "🇿🇦" },
  { code: "ZMW", name: "Zambian Kwacha", country: "Zambia", symbol: "ZK", flag: "🇿🇲" },
  { code: "ZWL", name: "Zimbabwean Dollar", country: "Zimbabwe", symbol: "Z$", flag: "🇿🇼" },
];

export function findCurrency(code?: string): CurrencyOption | undefined {
  if (!code) return undefined;
  const upper = code.toUpperCase();
  return ALL_CURRENCIES.find((c) => c.code === upper);
}
